packages:
  - playground
  - client

overrides:
  "@nuxt/a11y": "workspace:*"

allowBuilds:
  "@parcel/watcher": false
  esbuild: false
  unrs-resolver: false

minimumReleaseAgeExclude:
  - nuxt
  - nuxt-nightly
  - '@nuxt/*'
  - vue
  - '@vue/*'
